### PR TITLE
add prebuild

### PR DESCRIPTION
**Pull request by ralphtheninja**
`npm run prebuild` to build `hackrf` for all major abi versions (except for `0.10.x` which has some issues) and upload to github

`npm install hackrf` should then download prebuild binaries from github

@mappum You need a github token in e.g. `~/.prebuildrc` @mafintosh obviously knows all the details :)

### CODE REVIEW

**Comment by mafintosh** [comment]
Awesome!! Added prebuilds for 3.1.0 now for osx and linux (doesn't compile on win yet it seems)

**Comment by mappum** [comment]
Cool, thanks :+1:

`prebuild` looks awesome! However, I do wish it could sign the binaries after building (and verify the signatures on download). Would you guys be open to a PR?

**Comment by ralphtheninja** [comment]
> Would you guys be open to a PR?

@mappum +1

**Comment by mafintosh** [comment]
@mappum +1 (although npm modules are aren't signed so not sure how much security it adds)

**Pull request merged**
